Структура, BD, Docker
EvgeniyShmelev/java-explore-with-me pull request #1
Opened 2022-11-15 09:29 UTC by EvgeniyShmelev

2022-12-05 22:11 UTC, EvgeniyShmelev commented on ewm-service/src/main/java/ru/practicum/ewmmain/compilation/service/CompilationServiceImpl.java
> +    public CompilationDto add(NewCompilationDto newCompilationDto) {
Да да. Они должны быть) спасибо

2022-12-05 22:38 UTC, EvgeniyShmelev commented on ewm-service/src/main/java/ru/practicum/ewmmain/users/service/UserServiceImpl.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Повторение - мать ученья) забыл про эту штуку. Спасибо)

2022-12-05 23:43 UTC, EvgeniyShmelev commented on ewm-service/src/main/java/ru/practicum/ewmmain/categories/controller/AdminCategoryController.java
> +    public CategoryDto createCategory(@RequestBody NewCategoryDto newCategoryDto) {
Я перевел весь код в windows-1251, но кириллица все равно не читаема. Попробовал [эту](https://stackoverflow.com/questions/35231291/intellij-idea-incorrect-encoding-in-console-output) ссылку, результата все равно нет(

2022-12-06 04:36 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmmain/users/service/UserServiceImpl.java
> +        userRepository.findById(userId)
Суть в том что всего пользователя тебе не надо, ты удалешь по id
findById в общем случае будет строить запрос со всеми полями сущностями, со всеми джоинами если они есть (хотя в данном случае в сущности всего три поля, но все таки)

![image](https://user-images.githubusercontent.com/94845100/205815330-51b77617-c14b-4520-abf8-1702d1528db0.png)

existsById будет строить гораздо более простой запрос, конкретный запрос можно посмотреть в логе, он удет примерно таким

![image](https://user-images.githubusercontent.com/94845100/205815995-328b3988-598d-4bb6-b101-091df1fdf3e0.png)

https://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql


То есть логика тут рабочая, но есть небольшой момент который можно оптимизировать :)

2022-12-06 04:50 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmmain/categories/controller/AdminCategoryController.java
> +    public CategoryDto createCategory(@RequestBody NewCategoryDto newCategoryDto) {
Идея как раз нормально кодировку отображает, криво ее отображает гитхаб :)
Но кодировка все таки обычно используется utf-8, не у всех Винда и кодировка cp-1251

А вообще, кодировка настраивается, да и вообще почти все настройки проекта, в pom.xml

![image](https://user-images.githubusercontent.com/94845100/205818372-79111a36-ceb2-402f-8377-452701945778.png)

https://stackoverflow.com/questions/3017695/how-to-configure-encoding-in-maven

2022-12-06 04:53 UTC, EvgeniyShmelev commented on ewm-service/src/main/java/ru/practicum/ewmmain/users/service/UserServiceImpl.java
> +        userRepository.findById(userId)
Теперь понял) спасибо

2022-12-06 04:56 UTC, eugene-lenkevich requested changes
Привет, спасибо за доработку, попробуй все таки пофиксить кодировку, долго только не сиди с этим, не думаю что на самом деле супер-критично

2022-12-06 05:57 UTC, eugene-lenkevich approved these changes
Привет, ага, супер

Кстати, не везде починилась кодировка, я апрув поставлю, но, если будет время, то лучше тоже до ума довести :)

![image](https://user-images.githubusercontent.com/94845100/205830030-310b5094-99d3-4271-8243-671d0dd3a133.png)

2022-12-07 13:24 UTC, merged